# Generated by Django 5.2.5 on 2026-08-19 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(blank=True, max_length=255)),
                ('facility_type', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='e.g. 2025-01, 2025-Q1, 2025', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='reporting.program')),
            ],
            options={
                'ordering': ['program__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.CharField(choices=[('facilities', 'Facilities'), ('programs', 'Programs'), ('data', 'Program data')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'upload batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='reporting.facility')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='reporting.indicator')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='reporting.program')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='reporting.reportingperiod')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='reporting.uploadbatch')),
            ],
            options={
                'ordering': ['period__start_date', 'facility__name', 'indicator__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='indicator',
            constraint=models.UniqueConstraint(fields=('program', 'code'), name='unique_indicator_per_program'),
        ),
        migrations.AddIndex(
            model_name='datarecord',
            index=models.Index(fields=['facility', 'program', 'period'], name='reporting_d_facilit_af0139_idx'),
        ),
        migrations.AddConstraint(
            model_name='datarecord',
            constraint=models.UniqueConstraint(fields=('facility', 'program', 'indicator', 'period'), name='unique_record_per_facility_program_indicator_period'),
        ),
    ]
